In [1]:
import numpy as np
import pandas as pd
import geopandas as gpd
# import altair as alt
import json

In [2]:
df = gpd.read_file('../data/master.geojson')
temp = df.copy()
df.sample(3)

,id,name,illiterate,education,employed,unemployed,water,internet,men,women,...,cases2012,cases2013,cases2014,cases2015,cases2016,cases2017,cases2018,cases2019,area,geometry
479,25181,Choachí,3.14,49.98,37.14,3.13,10.55,60.07,49.95,50.05,...,3,1,0,2,0,0,0,1,0.017305,"POLYGON ((-73.793 4.637, -73.793 4.638, -73.79..."
272,15507,Otanche,9.62,40.69,40.13,5.05,44.27,74.96,51.31,48.69,...,37,5,74,63,72,18,0,44,0.038780,"POLYGON ((-74.079 5.833, -74.079 5.832, -74.07..."
138,8433,Malambo,4.95,59.55,32.98,6.39,4.56,58.62,49.63,50.37,...,153,337,359,415,81,22,157,181,0.008140,"POLYGON ((-74.812 10.879, -74.811 10.879, -74...."

In [3]:
# # population density
# temp["density2019"] = df["pop2019"] / (df["area"] / 1e6)

# (
#     alt.Chart(temp)
#     .mark_geoshape()
#     .encode(
#         tooltip=["name:N"],
#         color=alt.Color("density2019:Q", scale=alt.Scale(type="log", scheme="reds"))
#     )
#     .project(type="mercator")
#     .properties(width=600, height=600)
# )

In [4]:
# # possibly the unemployment rate
# temp["unemployment_rate"] = temp["unemployed"] / (temp["employed"] + temp["unemployed"])

# (
#     alt.Chart(temp)
#     .mark_geoshape()
#     .encode(
#         tooltip=["name:N", "unemployment_rate:Q"],
#         color=alt.Color("unemployment_rate:Q", scale=alt.Scale(type="log", scheme="blues"))
#     )
#     .project(type="mercator")
#     .properties(width=600, height=600)
# )

In [5]:
# # this shows the proportion of the population with internet access.
# temp["internet_access_rate"] = temp["internet"] / (temp["men"] + temp["women"])

# (
#     alt.Chart(temp)
#     .mark_geoshape()
#     .encode(
#         tooltip=["name:N", "internet_access_rate:Q"],
#         color=alt.Color("internet_access_rate:Q", scale=alt.Scale(type="log", scheme="greens"))
#     )
#     .project(type="mercator")
#     .properties(width=600, height=600)
# )